export const timeData  = [
        {
          'DateDone': '/Date(1622070000000)/',
          'FeeEarner': 'SUP',
          'Description': 'File Note',
          'Details': 'yryytut',
          'Units': 30,
          'USUnits': 0,
          'Value': 300,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1504134000000)/',
          'FeeEarner': 'SUP',
          'Description': 'Engineering time',
          'Details': 'Hat fashion',
          'Units': 4,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1504134000000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Attendance NO counsel - London',
          'Units': 3,
          'USUnits': 0,
          'Value': 44.7,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1504134000000)/',
          'FeeEarner': null,
          'Description': 'Attendance',
          'Details': 'Discard',
          'Units': 5,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1503874800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Attendance',
          'Details': 'Last test round',
          'Units': 8,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1503615600000)/',
          'FeeEarner': 'SUP',
          'Description': 'Engineering time',
          'Details': 'Test only',
          'Units': 4,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501110000000)/',
          'FeeEarner': 'NSZ',
          'Description': 'Preparation',
          'Details': 'chrome- 07-27\n\nIncluded header',
          'Units': 2,
          'USUnits': 0,
          'Value': 20,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501110000000)/',
          'FeeEarner': 'GN',
          'Description': null,
          'Details': 'Attendance Note',
          'Units': 4,
          'USUnits': 0,
          'Value': 2.4,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Engineering time',
          'Details': 'LO',
          'Units': 5,
          'USUnits': 0,
          'Value': 50,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': null,
          'Details': 'Email Out',
          'Units': 5,
          'USUnits': 0,
          'Value': 2.5,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Preparation',
          'Details': 'CO',
          'Units': 5,
          'USUnits': 0,
          'Value': 53.5,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'SUP',
          'Description': 'Engineering time',
          'Details': 'RE: rat with cat',
          'Units': 5,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Attendance',
          'Details': 'VariableListCR12_06_2017',
          'Units': 4,
          'USUnits': 0,
          'Value': 40,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Engineering time',
          'Details': 'LI',
          'Units': 4,
          'USUnits': 0,
          'Value': 40,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'AAU',
          'Description': 'Time Record Type 3',
          'Details': 'FW: MAT & HAT',
          'Units': 4,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Time Record Type 3',
          'Details': 'FW: Summarized  dates and deliverables for today\'s discussion',
          'Units': 3,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'GN',
          'Description': 'Preparation',
          'Details': 'CI',
          'Units': 4,
          'USUnits': 0,
          'Value': 41.6,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'SUP',
          'Description': 'Attendance',
          'Details': 'Himalayas',
          'Units': 6,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1501023600000)/',
          'FeeEarner': 'SUP',
          'Description': 'Attendance',
          'Details': '(DPS:1:GP:31014) great way to go',
          'Units': 6,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1500937200000)/',
          'FeeEarner': 'SUP',
          'Description': 'Engineering time',
          'Details': 'Decline - Clorin',
          'Units': 5,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1500937200000)/',
          'FeeEarner': 'GN',
          'Description': 'Engineering time',
          'Details': 'DPSRemote2015 Work Item Changed: Bug 2753 - Edge Browser: Cannot test through edge browser due to slowness',
          'Units': 4,
          'USUnits': 0,
          'Value': 40,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1499295600000)/',
          'FeeEarner': 'SUP',
          'Description': 'File Note',
          'Details': 'Routine letters ',
          'Units': 10,
          'USUnits': 0,
          'Value': 100,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1497481200000)/',
          'FeeEarner': 'SUP',
          'Description': 'Engineering time',
          'Details': 'Screen Editor - test only',
          'Units': 5,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1494111600000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Email In',
          'Units': 7,
          'USUnits': 0,
          'Value': 105,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1494111600000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Final Hearing Fee Day FPC',
          'Units': 6,
          'USUnits': 0,
          'Value': 90,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1494111600000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Dion activity test',
          'Units': 7,
          'USUnits': 0,
          'Value': 105,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1494111600000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Heaering Unit 2 Private Children FPC',
          'Units': 3,
          'USUnits': 0,
          'Value': 45,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1494111600000)/',
          'FeeEarner': 'SUP',
          'Description': null,
          'Details': 'Final Hearing Fee Day FPC',
          'Units': 3,
          'USUnits': 0,
          'Value': 45,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1493938800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': '(DPS:1:CR:31305) Mail inside mail with DPS file',
          'Units': 5,
          'USUnits': 0,
          'Value': 50,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1493938800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': '(DPS:1:GP:31014) tvb5y5yb 5y',
          'Units': 5,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1493938800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': 'Billing Guide',
          'Units': 4,
          'USUnits': 0,
          'Value': 40,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1492729200000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email In',
          'Details': '(DPS:38:MA:30307)',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1492642800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': 'des',
          'Units': 20,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1492642800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'des',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1492642800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': 'Ipad',
          'Units': 20,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1492642800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'Ipad',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491519600000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': 'paging - Copy',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491433200000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': '64774629-0e8c-4389-8aa5-c34e5a556458',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': 'GetPersonaPhoto',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'AAU',
          'Description': 'Email In',
          'Details': '(DPS:1:GP:31014) test',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'test',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': 'processing',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': 'test',
          'Units': 2,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1491346800000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': 'unnamed',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1490054400000)/',
          'FeeEarner': 'SUP',
          'Description': 'Preparation',
          'Details': 'Flower deco',
          'Units': 9,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1490054400000)/',
          'FeeEarner': 'AJC',
          'Description': 'Letter Out',
          'Details': 'Made Appointment for Client',
          'Units': 1,
          'USUnits': 0,
          'Value': 10,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1490054400000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'Flower deco',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1489622400000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'Test only',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1489536000000)/',
          'FeeEarner': 'AAU',
          'Description': 'Letter In',
          'Details': 'Test 111',
          'Units': 1,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        },
        {
          'DateDone': '/Date(1489536000000)/',
          'FeeEarner': 'SUP',
          'Description': 'Email Out',
          'Details': 'Dear friends',
          'Units': 0,
          'USUnits': 0,
          'Value': 0,
          'Billed': false,
          'DateBilled': null,
          'NetBilled': 0,
          'BillNo': null
        }
      ];
