export const SEARCH_VIEW_ID = 'DRIVE_SEARCH_VIEW';

export const SAFE_BOX_DRIVE_TOKEN = 'SAFE_BOX_DRIVE_TOKEN';
export const POPUP_DRIVE_TOKEN = 'POPUP_DRIVE_TOKEN';

export const SESSION_UPLOAD_MAX = 32768000;
